# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainForm(object):
    def setupUi(self, mainForm):
        mainForm.setObjectName("mainForm")
        mainForm.setEnabled(True)
        mainForm.resize(1185, 521)
        self.groupBox = QtWidgets.QGroupBox(mainForm)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 521, 291))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 210, 161, 17))
        self.label.setObjectName("label")
        self.detailsCount = QtWidgets.QSpinBox(self.groupBox)
        self.detailsCount.setGeometry(QtCore.QRect(460, 210, 48, 26))
        self.detailsCount.setObjectName("detailsCount")
        self.machineCount = QtWidgets.QComboBox(self.groupBox)
        self.machineCount.setGeometry(QtCore.QRect(180, 210, 86, 25))
        self.machineCount.setObjectName("machineCount")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(300, 210, 151, 17))
        self.label_2.setObjectName("label_2")
        self.startCalculationButton = QtWidgets.QPushButton(self.groupBox)
        self.startCalculationButton.setGeometry(QtCore.QRect(420, 250, 91, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.startCalculationButton.setPalette(palette)
        self.startCalculationButton.setObjectName("startCalculationButton")
        self.saveButton = QtWidgets.QPushButton(self.groupBox)
        self.saveButton.setGeometry(QtCore.QRect(110, 250, 89, 25))
        self.saveButton.setObjectName("saveButton")
        self.loadButton = QtWidgets.QPushButton(self.groupBox)
        self.loadButton.setGeometry(QtCore.QRect(10, 250, 89, 25))
        self.loadButton.setObjectName("loadButton")
        self.initialQueueTableView = QtWidgets.QTableView(self.groupBox)
        self.initialQueueTableView.setGeometry(QtCore.QRect(10, 30, 501, 171))
        self.initialQueueTableView.setObjectName("initialQueueTableView")
        self.alterMethodCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.alterMethodCheckBox.setGeometry(QtCore.QRect(220, 250, 191, 21))
        self.alterMethodCheckBox.setObjectName("alterMethodCheckBox")
        self.groupBox_2 = QtWidgets.QGroupBox(mainForm)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 310, 521, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.optimizedQueueTableView = QtWidgets.QTableView(self.groupBox_2)
        self.optimizedQueueTableView.setGeometry(QtCore.QRect(10, 30, 501, 161))
        self.optimizedQueueTableView.setObjectName("optimizedQueueTableView")
        self.diagramLabel = QtWidgets.QLabel(mainForm)
        self.diagramLabel.setEnabled(False)
        self.diagramLabel.setGeometry(QtCore.QRect(540, 30, 112, 17))
        self.diagramLabel.setObjectName("diagramLabel")

        self.retranslateUi(mainForm)
        QtCore.QMetaObject.connectSlotsByName(mainForm)

    def retranslateUi(self, mainForm):
        _translate = QtCore.QCoreApplication.translate
        mainForm.setWindowTitle(_translate("mainForm", "Решение задачи Джонсона"))
        self.groupBox.setTitle(_translate("mainForm", "Исходные данные"))
        self.label.setText(_translate("mainForm", "Количество агрегатов"))
        self.label_2.setText(_translate("mainForm", "Количество деталей"))
        self.startCalculationButton.setText(_translate("mainForm", "Рассчитать"))
        self.saveButton.setText(_translate("mainForm", "Сохранить"))
        self.loadButton.setText(_translate("mainForm", "Загрузить"))
        self.alterMethodCheckBox.setToolTip(_translate("mainForm", "<html><head/><body><p>При установке данного флага производится расчет оптимальной последовательности по суммам Ai+Bi и Bi+Ci</p></body></html>"))
        self.alterMethodCheckBox.setText(_translate("mainForm", "Альтернативный метод"))
        self.groupBox_2.setTitle(_translate("mainForm", "Результат оптимизации"))
        self.diagramLabel.setText(_translate("mainForm", "Нет диаграммы"))
